### ISSUE TITLE
Monospace Font

### ISSUE THREAD

**Issue by Zer0t3ch** [jneilliii/OctoPrint-M117NavBar#1]
Is it possible to make this use a monospace font so it more similarly emulates what the text looks like on the printer's LCD?

**Comment by jneilliii** [comment]
I personally wouldn't add this to the plugin, but you should be able to achieve this with [Themeify](https://plugins.octoprint.org/plugins/themeify/).  You would just add a custom css style for `span#M117NavBar` css rule `font-family` value of `monospace`.

![image](https://user-images.githubusercontent.com/5249455/42189074-a72c293a-7e24-11e8-9bca-20983dffb40b.png)
